apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-fe-cm
  namespace: mlr-dev-fe-ns
data:
  NEXT_PUBLIC_API_URL: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-de-cm
  namespace: mlr-dev-be-ns
data:
  DATABASE_URL:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-db-cm
  namespace: mlr-dev-db-ns
data: