apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-fe-cm
  namespace: mlr-dev-fe-ns
data:
  API_URL: "http://mlr-dev-be-svc-nod.mlr-dev-be-ns.svc.cluster.local:3000"
  FAST_API_URL: "http://mlr-dev-be-svc-fap.mlr-dev-be-ns.svc.cluster.local:5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-be-cm-nod
  namespace: mlr-dev-be-ns
data:
  MONGO_URI: "mongodb://mlr-dev-db-sfs-0.mlr-dev-db-svc-sfs.mlr-dev-db-ns.svc.cluster.local:27017,mlr-dev-db-sfs-1.mlr-dev-db-svc-sfs.mlr-dev-db-ns.svc.cluster.local:27017,mlr-dev-db-sfs-2.mlr-dev-db-svc-sfs.mlr-dev-db-ns.svc.cluster.local:27017/mlrDB?replicaSet=rs0&readPreference=secondary"
# MONGO_PRI_URI: “mlr-dev-db-pri-svc.mlr-dev-db-ns.svc-cluster.local:27017"
# MONGO_SCD_URI: “mlr-dev-db-scd-svc.mlr-dev-db-ns.svc-cluster.local:27017"
  FRONT_URI: "https://192.168.0.206:32423"
  KAKAO_REDIRECT_URI: "https://192.168.0.206:32423/back/auth/kakao/redirect"
  KAKAO_SCOPE: "openid,account_email"
  NAVER_REDIRECT_URI: "https://192.168.0.206:32423/back/auth/naver/redirect"
  NAVER_STATE: "1234567890"
  GOOGLE_REDIRECT_URI: "https://192.168.0.206:32423/back/auth/google/redirect"
  GOOGLE_SCOPE: "openid email"
