apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlr-dev-fe-ing
  namespace: mlr-dev-fe-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlr-dev-fe-svc
            port:
              number: 4000
  tls:
  - hosts:
    - book.mylittle.recipes
    secretName: mlr-dev-tls-sec
