apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-fe-dpl
  namespace: mlr-dev-fe-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:init
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-fe-cm
              key: API_URL
        - name: FAST_API_URL
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-fe-cm
              key: FAST_API_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-be-dpl
  namespace: mlr-dev-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 192.168.56.200/mylittlerecipebook/mlr-dev-be-img:init
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: MONGO_URI
        - name: FRONT_URI
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: FRONT_URI
        - name: KAKAO_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: KAKAO_REDIRECT_URI
        - name: KAKAO_SCOPE
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: KAKAO_SCOPE
        - name: NAVER_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: NAVER_REDIRECT_URI
        - name: NAVER_STATE
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: NAVER_STATE
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: GOOGLE_REDIRECT_URI
        - name: GOOGLE_SCOPE
          valueFrom:
            configMapKeyRef:
              name: mlr-dev-be-cm-nod
              key: GOOGLE_SCOPE
        - name: KAKAO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: KAKAO_CLIENT_ID
        - name: KAKAO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: KAKAO_CLIENT_SECRET
        - name: NAVER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: NAVER_CLIENT_ID
        - name: NAVER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: NAVER_CLIENT_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-nod
              key: GOOGLE_CLIENT_SECRET
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: mlr-dev-be-sec-fap
              key: YOUTUBE_API_KEY
